name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Force Compiling Without Loom
        run: |
          mkdir -p build/libs
          javac -d build/libs $(find src/main/java -name "*.java")
          cd build/libs
          jar cvf radiumaddon-1.0.0.jar .
          
      - name: Upload Final Mod File
        uses: actions/upload-artifact@v4
        with:
          name: RadiumAddon-Jar
          path: build/libs/*.jar
          
