name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Setup Gradle Without Broken Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'
          cache-disabled: true # Zwingt den Server, den kaputten Cache zu ignorieren!

      - name: Force Wrapper Generation
        run: gradle wrapper --gradle-version 8.8

      - name: Grant Execute Permissions
        run: chmod +x gradlew
          
      - name: Clean And Build Mod
        run: ./gradlew clean build --no-daemon -x test
        
      - name: Upload Final Mod File
        uses: actions/upload-artifact@v4
        with:
          name: RadiumAddon-Jar
          path: build/libs/*.jar
